# Site Settings
locale                   : "en-US"
title                    : "Kristoffer K. Wickstrøm"
title_separator          : "-"
name                     : "Kristoffer K. Wickstrøm"
description              : "Associate professor in machine learning at UiT The Arctic University of Norway"
url                      : https://wickstrom.github.io
baseurl                  : ""
repository               : "wickstrom/wickstrom.github.io"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

atom_feed:
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "Kristoffer K. Wickstrøm"
  avatar           : "profile-pic-kw.png"
  bio              : "Associate professor in machine learning at UiT The Arctic University of Norway"
  location         : "Tromsø, Norway"
  googlescholar    : "https://scholar.google.no/citations?user=gUd35ngAAAAJ&hl=no"
  email            : "kristoffer.k.wickstrom@uit.no"
  researchgate     : "https://www.researchgate.net/profile/Kristoffer-Wickstrom"
  github           : "wickstrom"
  linkedin         : "kriwick"
  orcid            : "https://orcid.org/0000-0003-1395-7154"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Gemfile
  - LICENSE
  - README
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: /:categories/:title/
timezone: Europe/Oslo


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-sitemap
  - jekyll-feed


# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
